name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.vscode/**'
      - 'coverage/**'
      - '**.md'
  pull_request:
    tags:
      - '!*'
    branches:
      - '*'
    paths-ignore:
      - '.vscode/**'
      - 'coverage/**'
      - '**.md'
  workflow_dispatch:

jobs:
  ci:
    name: 'Run tests: Node ${{ matrix.node }} on ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [
            'lts/*', # latest node
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cloning repository
        uses: actions/checkout@v3

      - name: 'Setting up Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies & build
        run: |
          npm ci --ignore-scripts
          npm run compile-tests

      - name: Format (prettier)
        run: npm run format:check

      - name: Lint (eslint)
        run: npm run lint

      # - name: Integration tests
      #   # see https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
      #   run: xvfb-run -a npm run test
      #   shell: bash
