name: Release

env:
  NODE_VERSION: 'lts/*'

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

      - name: 'Setting up Node.js ${{ env.NODE_VERSION }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Installing dependencies
        run: npm ci

      # - name: Publish to Visual Studio Marketplace
      #   run: npx vsce@2.9.2 publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Package Extension
        id: packageExtension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: stub
          dryRun: true

      # - name: Upload Extension Package as Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ matrix.os }}
      #     path: ${{ steps.packageExtension.outputs.vsixPath }}

      # - name: Create the .vsix file
      #   run: vsce package

      - name: Upload VSIX file to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: vscode-marketplace-preview-*.*.*.vsix
          overwrite: true
          tag: ${{ github.ref }}

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ steps.packageExtension.outputs.vsixPath }}

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.packageExtension.outputs.vsixPath }}
